import { toast } from 'vue-sonner';

import { useExternalLinkStore, useSearchStore } from '../../stores';
import { escapeTag } from './base/string';
import { i18n } from '../../plugins/i18n';

/**
 * @param {string} fileName
 * @param {any} data
 */
function downloadAndSaveJson(fileName, data) {
    if (!fileName || !data) {
        return;
    }
    try {
        const link = document.createElement('a');
        link.setAttribute(
            'href',
            `data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(data, null, 2))}`
        );
        link.setAttribute('download', `${fileName}.json`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch {
        toast.error(escapeTag('Failed to download JSON.'));
    }
}

/**
 * @param {string} text
 * @param {string} message
 */
function copyToClipboard(text, message = 'Copied successfully!') {
    navigator.clipboard
        .writeText(text)
        .then(() => {
            toast.success(message);
        })
        .catch((err) => {
            console.error('Copy failed:', err);
            toast.error(i18n.global.t('message.copy_failed'));
        });
}

/**
 * @param {string} link
 */
function openExternalLink(link) {
    const searchStore = useSearchStore();
    if (searchStore.directAccessParse(link)) {
        return;
    }

    const externalLinkStore = useExternalLinkStore();
    externalLinkStore.showExternalLinkDialog(link);
}

/**
 * Route ordinary external anchors (including links generated by markdown)
 * through the same confirmation and native default-browser flow.
 * @param {Document | HTMLElement} root
 * @returns {() => void}
 */
function installExternalLinkHandler(root = document) {
    const handleClick = (event) => {
        if (event.defaultPrevented || !(event.target instanceof Element)) {
            return;
        }

        const anchor = event.target.closest('a[href]');
        if (!anchor || anchor.hasAttribute('download')) return;

        const href = anchor.getAttribute('href');
        if (!href || href.startsWith('#')) return;

        let url;
        try {
            url = new URL(href, window.location.href);
        } catch {
            return;
        }

        if (
            !['http:', 'https:'].includes(url.protocol) ||
            url.origin === window.location.origin
        ) {
            return;
        }

        event.preventDefault();
        openExternalLink(url.href);
    };

    root.addEventListener('click', handleClick);
    return () => root.removeEventListener('click', handleClick);
}

function openDiscordProfile(discordId) {
    if (!discordId) {
        toast.error('No Discord ID provided!');
        return;
    }
    AppApi.OpenDiscordProfile(discordId).catch((err) => {
        console.error('Failed to open Discord profile:', err);
        toast.error('Failed to open Discord profile!');
    });
}

// #region | App: Random unsorted app methods, data structs, API functions, and an API feedback/file analysis event

function openFolderGeneric(path) {
    AppApi.OpenFolderAndSelectItem(path, true);
}

export {
    downloadAndSaveJson,
    copyToClipboard,
    openExternalLink,
    installExternalLinkHandler,
    openDiscordProfile,
    openFolderGeneric
};
